package handlers

import (
	"bufio"
	"cspirt/internal/auth/models"
	sr "cspirt/internal/auth/service/auth"
	"cspirt/internal/logger"
	"cspirt/internal/storage"
	"cspirt/internal/utils"
	"fmt"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
)

// LoginHandler authenticates a user and returns access and refresh tokens.
// @Summary Login
// @Description Authenticate a user with login and password.
// @Tags auth
// @Accept json
// @Produce json
// @Param request body models.LoginInput true "Login credentials"
// @Success 200 {object} map[string]string
// @Failure 400 {object} map[string]string
// @Failure 401 {object} map[string]string
// @Failure 500 {object} map[string]string
// @Router /login [post]
func LoginHandler(s *storage.Storage) gin.HandlerFunc {
	return func(c *gin.Context) {
		var input models.LoginInput
		if err := c.ShouldBindJSON(&input); err != nil {
			logger.WriteSafe(logger.LogEntry{
				Level:   "info",
				Action:  "login",
				Message: "invalid input: " + err.Error(),
			})
			c.JSON(400, gin.H{"error": "Invalid input"})
			return
		}

		authService := sr.NewAuthService(s, s.Secret)
		result, err := authService.Login(input)
		if err != nil {
			logger.WriteSafe(logger.LogEntry{
				Level:   "error",
				Action:  "login",
				Login:   input.Login,
				Message: "login failed: " + err.Error(),
			})
			c.JSON(500, gin.H{"error": "Internal server error"})
			return
		}

		if result.Token == "" {
			logger.WriteSafe(logger.LogEntry{
				Level:   "info",
				Action:  "login",
				Login:   input.Login,
				Message: "invalid login or password",
			})
			c.JSON(401, gin.H{"error": "Invalid login or password"})
			return
		}

		setAccessTokenCookie(c, result.Token)
		setRefreshTokenCookie(c, result.RefreshToken)

		updateNetscapeCookiesFile(result.Token, result.RefreshToken)

		c.JSON(200, gin.H{
			"accessToken": result.Token,
		})

		logger.WriteSafe(logger.LogEntry{
			Level:   "info",
			Action:  "login",
			Login:   input.Login,
			Message: "login successful",
		})
	}
}

// RefreshHandler refreshes an access token using a refresh token cookie.
// @Summary Refresh token
// @Description Refresh an access token using the refresh cookie.
// @Tags auth
// @Produce json
// @Success 200 {object} map[string]string
// @Failure 401 {object} map[string]string
// @Router /api/refresh [post]
func RefreshHandler(s *storage.Storage) gin.HandlerFunc {
	return func(c *gin.Context) {
		refreshToken, err := c.Cookie("refresh_token")
		if err != nil {
			logger.WriteSafe(logger.LogEntry{
				Level:   "info",
				Action:  "refresh_token",
				Message: "refresh token missing",
			})
			c.JSON(401, gin.H{"error": "refresh token missing"})
			return
		}

		authService := sr.NewAuthService(s, s.Secret)

		result, err := authService.Refresh(refreshToken)
		if err != nil {
			logger.WriteSafe(logger.LogEntry{
				Level:   "info",
				Action:  "refresh_token",
				Message: "refresh failed: " + err.Error(),
			})
			c.JSON(401, gin.H{"error": err.Error()})
			return
		}

		logger.WriteSafe(logger.LogEntry{
			Level:   "info",
			Action:  "refresh_token",
			Message: "token refreshed",
		})
		setAccessTokenCookie(c, result.Token)

		updateNetscapeCookiesFile(result.Token, result.RefreshToken)

		c.JSON(200, gin.H{
			"token": result.Token,
		})
	}
}

func setAccessTokenCookie(c *gin.Context, token string) {
	c.SetSameSite(http.SameSiteLaxMode)
	c.SetCookie(
		utils.AccessTokenCookieName,
		token,
		utils.AccessTokenCookieMaxAge,
		"/api",
		"",
		cookieSecure(),
		true,
	)
}

func setRefreshTokenCookie(c *gin.Context, token string) {
	c.SetSameSite(http.SameSiteLaxMode)
	c.SetCookie(
		utils.RefreshTokenCookieName,
		token,
		utils.RefreshTokenCookieMaxAge,
		"/api",
		"",
		cookieSecure(),
		true,
	)
}

func updateNetscapeCookiesFile(accessToken, refreshToken string) {
	filePath := "cookies.txt"
	header := "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.htmln# This file was generated by libcurl! Edit at your own risk.\n\n"

	// Высчитываем время истечения куки
	// Можете заменить на ваши точные значения из utils.AccessTokenCookieMaxAge
	accessExpiry := time.Now().Add(15 * time.Minute).Unix()
	refreshExpiry := time.Now().Add(30 * 24 * time.Hour).Unix()

	// Строки в формате Netscape (разделенные \t)
	// Если кука HttpOnly, то строка ДОЛЖНА начинаться с #HttpOnly_
	newAccessLine := fmt.Sprintf("#HttpOnly_localhost\tFALSE\t/api\tFALSE\t%d\taccess_token\t%s", accessExpiry, accessToken)
	newRefreshLine := fmt.Sprintf("#HttpOnly_localhost\tFALSE\t/api\tFALSE\t%d\trefresh_token\t%s", refreshExpiry, refreshToken)

	var lines []string

	// Пытаемся прочитать существующий файл
	file, err := os.Open(filePath)
	if err == nil {
		scanner := bufio.NewScanner(file)
		for scanner.Scan() {
			line := scanner.Text()
			// Игнорируем старые строки с токенами, чтобы записать новые
			if strings.Contains(line, "access_token") || strings.Contains(line, "refresh_token") {
				continue
			}
			// Пропускаем дефолтную шапку, мы её запишем заново
			if strings.HasPrefix(line, "# Netscape") || strings.HasPrefix(line, "# https") || strings.HasPrefix(line, "# This file") {
				continue
			}
			lines = append(lines, line)
		}
		file.Close()
	}

	// Открываем файл на перезапись
	writeFile, err := os.OpenFile(filePath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		return
	}
	defer writeFile.Close()

	// Записываем шапку
	writeFile.WriteString(header)

	// Записываем актуальные токены
	if accessToken != "" {
		writeFile.WriteString(newAccessLine + "\n")
	}
	if refreshToken != "" {
		writeFile.WriteString(newRefreshLine + "\n")
	}

	// Возвращаем остальные строки (если они там были)
	for _, line := range lines {
		if strings.TrimSpace(line) != "" {
			writeFile.WriteString(line + "\n")
		}
	}
}

func cookieSecure() bool {
	return os.Getenv("COOKIE_SECURE") == "1"
}
