name: Deploy Go Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.5"

      - name: Download dependencies
        run: go mod download

      - name: Build application
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
          go build -o cspirt ./cmd/app

      - name: Verify binary
        run: |
          ls -lah
          file cspirt

      - name: Upload binary
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "cspirt"
          target: "/tmp"
          overwrite: true

      - name: Deploy and restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl stop cspirt.service
            sudo mv /tmp/cspirt /opt/cspirt/bin/cspirt
            sudo chmod +x /opt/cspirt/bin/cspirt
            sudo systemctl start cspirt.service
            sudo systemctl status cspirt.service --no-pager